
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/longzai_mall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 1000
  jedis:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8083
debug: true


# 上传文件的路径 根据部署情况 自行修改
file:
  upload:
    dir: /Users/myl/IdeaProjects/longzai-mall-prepare-static/
